# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-11 17:01
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cousrecomments',
            name='comments',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='课程评论'),
        ),
    ]
