# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=20, verbose_name='IP地址')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名称')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='生产厂家')),
                ('Memory', models.FloatField(verbose_name='内存')),
            ],
            options={
                'verbose_name_plural': '资产详情',
                'verbose_name': '资产详情',
            },
        ),
    ]
