# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-31 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='Memory',
            new_name='memory',
        ),
    ]
