# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-31 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180531_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
