# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-31 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='machinemodel',
            field=models.CharField(default='', max_length=50, verbose_name='机器型号'),
        ),
    ]
