# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-31 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_asset_machinemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='macaddress',
            field=models.CharField(default='', max_length=50, verbose_name='MAC地址'),
        ),
    ]
