# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_asset_macaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_production',
            field=models.CharField(choices=[('test', '测试'), ('production', '生产')], default='test', max_length=20, verbose_name='是否生产'),
        ),
    ]
