# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(default='', max_length=50, verbose_name='课程类别'),
        ),
    ]
